version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    environment:
      - PUID=1000
      - PGID=985
      - TZ=Asia/Jerusalem
    ports:
      - 32400:32400
    volumes:
      - ./plex-data:/config
      - ./media:/data
    networks:
      - media

  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=985
      - TZ=Asia/Jerusalem
      - WEBUI_PORT=9091
    volumes:
      - ./qbittorrent-data:/config
      - ./downloads:/downloads
    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=985
      - TZ=Asia/Jerusalem
    ports:
      - 8989:8989
    volumes:
      - ./sonarr-data:/config
      - ./downloads:/downloads
      - ./media/tv:/tv
    networks:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=985
      - TZ=Asia/Jerusalem
    ports:
      - 7878:7878
    volumes:
      - ./radarr-data:/config
      - ./downloads:/downloads
      - ./media/movies:/movies
    networks:
      - media

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      - PUID=1000
      - PGID=985
      - TZ=Asia/Jerusalem
    volumes:
      - ./overseerr-data:/config
    ports:
      - 5055:5055
    networks:
      - media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=985
      - TZ=Asia/Jerusalem
    volumes:
      - ./prowlarr-data:/config
    ports:
      - 9696:9696
    networks:
      - media

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - TZ=Asia/Jerusalem
    ports:
      - 8191:8191
    networks:
      - media

networks:
  media:
    external: true
